### ISSUE TITLE
Docs build failures

### ISSUE THREAD

**Issue by sanjayankur31** [INCF/nineml-python#41]
There are a few errors when building the docs using `make html`, I couldn't find an issue about this, so filing one here. Please close if it's been fixed. I was using the 1.0 version, not master.:

```
WARNING: autodoc: failed to import class 'AnalogPortConnection' from module 'nineml'; the following exception was raised:
Traceback (most recent call last):
  File "/home/asinha/dump/nineml-virt/lib64/python3.7/site-packages/sphinx/util/inspect.py", line 225, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'nineml' has no attribute 'AnalogPortConnection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/asinha/dump/nineml-virt/lib64/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 193, in import_object
    obj = attrgetter(obj, attrname)
  File "/home/asinha/dump/nineml-virt/lib64/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 290, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/asinha/dump/nineml-virt/lib64/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 1562, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/asinha/dump/nineml-virt/lib64/python3.7/site-packages/sphinx/util/inspect.py", line 241, in safe_getattr
    raise AttributeError(name)
AttributeError: AnalogPortConnection

WARNING: autodoc: failed to import class 'EventPortConnection' from module 'nineml'; the following exception was raised:
Traceback (most recent call last):
  File "/home/asinha/dump/nineml-virt/lib64/python3.7/site-packages/sphinx/util/inspect.py", line 225, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'nineml' has no attribute 'EventPortConnection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/asinha/dump/nineml-virt/lib64/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 193, in import_object
    obj = attrgetter(obj, attrname)
  File "/home/asinha/dump/nineml-virt/lib64/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 290, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/asinha/dump/nineml-virt/lib64/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 1562, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/asinha/dump/nineml-virt/lib64/python3.7/site-packages/sphinx/util/inspect.py", line 241, in safe_getattr
    raise AttributeError(name)
AttributeError: EventPortConnection
```

**Comment by tclose** [comment]
Sorry Ankur, I only just noticed this issue now. The docs are building in my dev branch so once that is merged it should be okay. In the mean time can you just refer to the readthedocs version?

**Comment by sanjayankur31** [comment]
Sure. No worries. This was for the [NeuroFedora package](https://src.fedoraproject.org/rpms/python-nineml). I've disabled the docs build for the moment and point to online docs.

Please close this ticket whenever you see it fit. 

Thanks again :)

**Comment by tclose** [comment]
Okay, thanks
